feat: add property level maturity + ga4gh prefix/keys in RST files
ga4gh/gks-metaschema pull request #29
Opened 2024-11-04 21:33 UTC by korikuzma

close #26

* Add GA4GH Digest table if prefix/keys are provided
* Add Flags column for property level maturity status + ordered property in arrays

2024-11-05 04:53 UTC, korikuzma commented on src/ga4gh/gks/metaschema/scripts/y2t.py
> +    "trial_use": ("FFFF99", "TU"),
not sure the convention that the source yaml files will follow...

2024-11-05 04:53 UTC, korikuzma commented on src/ga4gh/gks/metaschema/scripts/y2t.py
> +    "trial_use": ("FFFF99", "TU"),
@ahwagner @larrybabb

2024-11-05 04:53 UTC, korikuzma commented on src/ga4gh/gks/metaschema/scripts/y2t.py
> +        ga4gh_prefix = ga4gh_digest.get("prefix") or "None"
Is it okay to display None?

2024-11-05 04:54 UTC, korikuzma commented on src/ga4gh/gks/metaschema/scripts/y2t.py
> +    *  - {ga4gh_digest.get("prefix") or "None"}
Is it okay to display this as None?

2024-11-05 06:00 UTC, larrybabb requested changes
love the changes. However, I think we need some more discrete and distinct indicator for the `UL` and `OL` flags. I think the icons for `N`, `D` and `TU` are special because they represent the styling that is for maturity levels based on the same styling as FHIR. But `UL` and `OL` should be changed to something like a unicode characters such as 
a down arrow for U+2193 for ordered lists and 3 vertical elipses for unordered lists U+22EE

2024-11-05 13:21 UTC, korikuzma commented
Latest changes

<img width="534" alt="Screenshot 2024-11-05 at 08 20 52" src="https://github.com/user-attachments/assets/8cab6bfc-b854-4c72-91ac-c5d6e9acafcb">

<img width="534" alt="Screenshot 2024-11-05 at 08 21 15" src="https://github.com/user-attachments/assets/edb8afd5-aae8-44e5-a441-c30f7b0bdfa9">

2024-11-07 01:20 UTC, larrybabb approved these changes

2024-11-07 01:21 UTC, larrybabb commented
going for it.

2024-11-07 01:21 UTC, merged